// Generated by Wrangler on Wed Jul 31 2024 16:40:26 GMT+0800 (Australian Western Standard Time)
// by running `wrangler types`

interface Env {
  CLIENT_ID: string;
  CLIENT_SECRET: string;
  REDIRECT_URI: string;
}
